-- Script MySQL para el borrado de la base de datos
-- Autores
    -- Francisco Beltŕan Sánchez
    -- Pablo Cordero Romero
    -- Francisco Domínguez Lorente
    -- David Gómez Hernández
    -- Miguel Ángel Posadas Arráez

DROP TABLE comprasiniciadas CASCADE CONSTRAINTS;
DROP TABLE compraspagadas CASCADE CONSTRAINTS;
DROP TABLE comprasPorUsuariosEnEdicion CASCADE CONSTRAINTS;
DROP TABLE comprasfinalizadas CASCADE CONSTRAINTS;
DROP TABLE ofertasaceptadas CASCADE CONSTRAINTS;
DROP TABLE ofertasrechazadas CASCADE CONSTRAINTS;
DROP TABLE contraofertasaceptadas CASCADE CONSTRAINTS;
DROP TABLE contraofertasrechazadas CASCADE CONSTRAINTS;
DROP TABLE arbitra CASCADE CONSTRAINTS;
DROP TABLE ofertar CASCADE CONSTRAINTS;
DROP TABLE contraofertar CASCADE CONSTRAINTS;
DROP TABLE contrato CASCADE CONSTRAINTS;
DROP TABLE contiene CASCADE CONSTRAINTS;
DROP TABLE trabaja CASCADE CONSTRAINTS;
DROP TABLE participan CASCADE CONSTRAINTS;
DROP TABLE asignar CASCADE CONSTRAINTS;
DROP TABLE juegan CASCADE CONSTRAINTS;
DROP TABLE edicion CASCADE CONSTRAINTS;
DROP TABLE trabajadores CASCADE CONSTRAINTS;
DROP TABLE pistas CASCADE CONSTRAINTS;
DROP TABLE partidos CASCADE CONSTRAINTS;
DROP TABLE jugadores CASCADE CONSTRAINTS;
DROP TABLE arbitros CASCADE CONSTRAINTS;
DROP TABLE entradas CASCADE CONSTRAINTS;
DROP TABLE ofertas CASCADE CONSTRAINTS;
DROP TABLE contraofertas CASCADE CONSTRAINTS;
DROP TABLE usuarios CASCADE CONSTRAINTS;
DROP TABLE partidosenpista CASCADE CONSTRAINTS;